version: '3.8'

services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data

  api:
    image: python:3.10-slim
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ./requirements.txt:/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - YOUTUBE_API_KEY
    command: bash -lc "pip install -r /requirements.txt && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    image: python:3.10-slim
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ./requirements.txt:/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - YOUTUBE_API_KEY
    command: bash -lc "pip install -r /requirements.txt && python /app/worker/worker.py"
    depends_on:
      - redis

  mcp:
    build:
      context: .
      dockerfile: mcp/Dockerfile
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ./requirements.txt:/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - YOUTUBE_API_KEY
    command: bash -lc "pip install -r /requirements.txt && uvicorn mcp.youtube_researcher_server:app --host 0.0.0.0 --port 8002 --reload"
    ports:
      - "8002:8002"
    depends_on:
      - redis

volumes:
  redis-data:
