version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

# Optional: run the API locally using uvicorn
# api:
#   build: .
#   command: uvicorn api.main:app --host 0.0.0.0 --port 8000
#   ports:
#     - "8000:8000"
#   environment:
#     - REDIS_HOST=redis
#   depends_on:
#     - redis
