version: '3.8'

services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data

  api:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./api:/app
      - ./requirements.txt:/requirements.txt
      - ./webui:/app/webui
    command: bash -lc "pip install -r /requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    image: python:3.10-slim
    working_dir: /worker
    volumes:
      - ./worker:/worker
      - ./requirements.txt:/requirements.txt
    command: bash -lc "pip install -r /requirements.txt && python /worker/worker.py"
    depends_on:
      - redis
      - model_runner

  model_runner:
    build: ./model_runner
    image: swarm-model-runner:latest
    working_dir: /app
    volumes:
      - ./model_runner:/app
      - ./model_runner/models:/app/models
    command: bash -lc "pip install -r /app/requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8001 --reload"
    ports:
      - "8001:8001"
    depends_on:
      - redis

volumes:
  redis-data:
