name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run mypy
        env:
          PYTHONPATH: .
        run: |
          python -m mypy --config-file mypy.ini

      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          python -m pytest -q

      - name: Prompt validation
        env:
          PYTHONPATH: .
        run: |
          python -m scripts.validate_prompts --paths prompts.json --report-json validation-report.json
