name: Markdown format check

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  mdformat-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install mdformat
        run: python -m pip install --upgrade pip && python -m pip install mdformat
      - name: Run mdformat check
        run: python -m mdformat --check .
